version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.2
    steps:
      - run: go get golang.org/x/lint/golint
      - run: go get github.com/mitchellh/gox
      - run: go get github.com/tcnksm/ghr
      - checkout
      - run: golint
      # workaround for https://github.com/golang/go/issues/27925
      - run: sed -e '/^k8s.io\/client-go /d' -i go.sum
      - run: go vet
      - run: make dist
      # release to GitHub on tag push
      - run: |
          if [ "$CIRCLE_TAG" ]; then
            ghr -u "$CIRCLE_PROJECT_USERNAME" -r "$CIRCLE_PROJECT_REPONAME" "$CIRCLE_TAG" dist
          fi

workflows:
  version: 2
  all:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
