version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.2
    steps:
      - run: |
          mkdir -p ~/bin
          echo 'export PATH="$HOME/bin:$PATH"' >> $BASH_ENV
      - run: |
          curl -L -o ~/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.14.0/bin/linux/amd64/kubectl
          chmod +x ~/bin/kubectl
      - run: go get golang.org/x/lint/golint
      - run: go get github.com/tcnksm/ghr
      - run: go get github.com/Songmu/ghch/cmd/ghch
      - run: go get github.com/int128/ghcp
      - checkout
      # workaround for https://github.com/golang/go/issues/27925
      - run: sed -e '/^k8s.io\/client-go /d' -i go.sum
      - run: make check
      - run: make run
      - run: |
          if [ "$CIRCLE_TAG" ]; then
            make release
          fi

workflows:
  version: 2
  all:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
